#!/usr/bin/bash
set -e

export BSYS6="$(dirname $(readlink -f "$0"))/src"
export ENTRY_PWD="$(pwd)"

if [ "$#" -eq 0 ]; then
  set -- "help"
fi

args="$@"
set --

for command in $args; do
  if [ "$command" == "--help" ] || [ "$command" == "-h" ]; then
    command="help"
  fi
  source $BSYS6/$command.sh
done

for artifact in $AVAILABLE_ARTIFACTS; do
  if [ -n "${!artifact:-}" ]; then
    if [ -z "${found_artifact:-}" ]; then
      echo "-> The following artifacts are available:"
      found_artifact=1
    fi
    echo "  $artifact: ${!artifact}"
  fi
done
