name: Docker Image

on:
  workflow_dispatch:

jobs:
  build-images:
    runs-on: epsilon
    container:
      image: codeberg.org/librewolf/bsys6:dind
    strategy:
      matrix:
        target: [windows, macos, linux, dind, release]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to Container Registry
        uses: docker/login-action@v4
        with:
          registry: codeberg.org
          username: ${{ vars.FORGE_USER }}
          password: ${{ secrets.FORGE_TOKEN }}

      - name: Build Docker Image
        env:
          TARGET: ${{ matrix.target }}
          FORGE_REPO: ${{ forgejo.repository }}
          FORGE_REPO_OWNER: ${{ forgejo.repository_owner }}
        run: |
          echo "Building docker for target: $TARGET using assets/Dockerfile.$TARGET"
          VERSION=$(curl -qfA "" --no-sessionid --proto =https --tlsv1.2 https://codeberg.org/api/v1/repos/librewolf/source/releases/latest | jq -r '.tag_name')
          docker build --progress=plain --no-cache -t "codeberg.org/$FORGE_REPO_OWNER/bsys6:$TARGET" --build-arg VERSION="$VERSION" . -f assets/Dockerfile.$TARGET
      - name: Push Docker Image
        run: |
          docker push codeberg.org/${{ forgejo.repository_owner }}/bsys6:${{ matrix.target }}
