name: Build & Publish Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Publish the release"
        required: false
        default: false
        type: boolean
      lto:
        description: "Build with LTO"
        required: false
        default: false
        type: boolean
      sign_exe:
        description: "Sign Windows executables"
        required: false
        default: true
        type: boolean
      sign_macos:
        description: "Sign macOS builds"
        required: false
        default: true
        type: boolean

jobs:
  build-linux:
    runs-on: epsilon
    container:
      image: librewolf.dev/librewolf/bsys6:linux
    strategy:
      max-parallel: 2
      matrix:
        arch: [x86_64, arm64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          lfs: false
          persist-credentials: false
      
      - name: Fetch LFS objects
        run: git lfs pull
  
      - name: Build Linux
        env:
          ARCH: ${{ matrix.arch }}
          SIGNING_KEY: ${{ forgejo.ref == 'refs/heads/master' && secrets.SIGNING_KEY || '' }}
          LTO: ${{ inputs.lto }}
        run: ./bsys6 package package_linux

      - name: Upload artifacts
        env:
          S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
          S3_ARTIFACTS_BUCKET: ${{ vars.S3_ARTIFACTS_BUCKET }}
          S3_ARTIFACTS_PUBLIC_URL: ${{ vars.S3_ARTIFACTS_PUBLIC_URL }}
          S3_KEY: ${{ secrets.S3_KEY }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
        run: ./bsys6 upload_artifacts

  build-windows:
    runs-on: epsilon
    container:
      image: librewolf.dev/librewolf/bsys6:windows
    strategy:
      max-parallel: 2
      matrix:
        arch: [x86_64, arm64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          lfs: false
          persist-credentials: false
      
      - name: Fetch LFS objects
        run: git lfs pull

      - name: Build Windows
        env:
          TARGET: windows
          ARCH: ${{ matrix.arch }}
          SIGNING_KEY: ${{ forgejo.ref == 'refs/heads/master' && secrets.SIGNING_KEY || '' }}
          LTO: ${{ inputs.lto }}
          OSSIGN_CONFIG: ${{ forgejo.ref == 'refs/heads/master' && secrets.OSSIGN_CONFIG || '' }}
          ENABLE_EXE_SIGNING: ${{ forgejo.ref == 'refs/heads/master' && inputs.sign_exe || false }}
        run: ./bsys6 package setup msix portable nupkg

      - name: Upload artifacts
        env:
          S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
          S3_ARTIFACTS_BUCKET: ${{ vars.S3_ARTIFACTS_BUCKET }}
          S3_ARTIFACTS_PUBLIC_URL: ${{ vars.S3_ARTIFACTS_PUBLIC_URL }}
          S3_KEY: ${{ secrets.S3_KEY }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
        run: ./bsys6 upload_artifacts

  build-macos:
    runs-on: epsilon
    container:
      image: librewolf.dev/librewolf/bsys6:macos
    strategy:
      max-parallel: 2
      matrix:
        arch: [x86_64, arm64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          lfs: false
          persist-credentials: false
      
      - name: Fetch LFS objects
        run: git lfs pull

      - name: Build MacOS
        env:
          TARGET: macos
          ARCH: ${{ matrix.arch }}
          SIGNING_KEY: ${{ forgejo.ref == 'refs/heads/master' && secrets.SIGNING_KEY || '' }}
          LTO: ${{ inputs.lto }}
          MACOS_SIGNING_P12: ${{ forgejo.ref == 'refs/heads/master' && inputs.sign_macos && secrets.MACOS_SIGNING_P12 || '' }}
          MACOS_NOTARY_KEY: ${{ forgejo.ref == 'refs/heads/master' && inputs.sign_macos && secrets.MACOS_NOTARY_KEY || '' }}
          MACOS_NOTARY_KEY_ID: ${{ forgejo.ref == 'refs/heads/master' && inputs.sign_macos && secrets.MACOS_NOTARY_KEY_ID || '' }}
          MACOS_NOTARY_ISSUER_ID: ${{ forgejo.ref == 'refs/heads/master' && inputs.sign_macos && secrets.MACOS_NOTARY_ISSUER_ID || '' }}
        run: ./bsys6 package

      - name: Upload artifacts
        env:
          S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
          S3_ARTIFACTS_BUCKET: ${{ vars.S3_ARTIFACTS_BUCKET }}
          S3_ARTIFACTS_PUBLIC_URL: ${{ vars.S3_ARTIFACTS_PUBLIC_URL }}
          S3_KEY: ${{ secrets.S3_KEY }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
        run: ./bsys6 upload_artifacts

  publish-release:
    if: forgejo.ref == 'refs/heads/master' && inputs.release
    runs-on: epsilon
    container:
      image: librewolf.dev/librewolf/bsys6:release
    needs: [build-linux, build-windows, build-macos]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Download artifacts
        env:
          S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
          S3_ARTIFACTS_BUCKET: ${{ vars.S3_ARTIFACTS_BUCKET }}
          S3_ARTIFACTS_PUBLIC_URL: ${{ vars.S3_ARTIFACTS_PUBLIC_URL }}
          S3_KEY: ${{ secrets.S3_KEY }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
        run: ./bsys6 download_artifacts

      - name: Publish Release
        env:
          FORGE_URL: ${{ forgejo.server_url }}
          FORGE_USER: ${{ vars.FORGE_USER }}
          FORGE_TOKEN: ${{ secrets.FORGE_TOKEN }}
          FORGE_REPO: ${{ forgejo.repository }}
          FORGE_REPO_OWNER: ${{ forgejo.repository_owner }}
          MIRROR_FORGE_URL: ${{ vars.MIRROR_FORGE_URL }}
          MIRROR_FORGE_REPO: ${{ vars.MIRROR_FORGE_REPO }}
          MIRROR_FORGE_REPO_OWNER: ${{ vars.MIRROR_FORGE_REPO_OWNER }}
          MIRROR_FORGE_USER: ${{ vars.MIRROR_FORGE_USER }}
          MIRROR_FORGE_TOKEN: ${{ secrets.MIRROR_FORGE_TOKEN }}
          REPO_DEPLOY_TOKEN: ${{ secrets.REPO_DEPLOY_TOKEN }}
          CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
          MS_CLIENT_SECRET: ${{ secrets.MS_CLIENT_SECRET }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          S3_ENDPOINT: ${{ vars.S3_ENDPOINT }}
          S3_BUCKET: ${{ vars.S3_BUCKET }}
          S3_KEY: ${{ secrets.S3_KEY }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
          S3_PUBLIC_URL: ${{ vars.S3_PUBLIC_URL }}
        run: ./bsys6 release
