name: Build & Publish Release

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: epsilon
    container:
      image: codeberg.org/librewolf/bsys6:linux
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Linux
        env:
           ARCH: ${{ matrix.arch }}
           SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run:
          ./bsys6 package deb rpm

      - name: Upload artifacts
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: linux-${{ matrix.arch }}
          path: |
            *.deb
            *.rpm
            *.tar.xz
            *.sha256sum
          retention-days: 7

  build-windows:
    runs-on: epsilon
    container:
      image: codeberg.org/librewolf/bsys6:windows 
    strategy:
      matrix:
        arch: [x86_64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Windows
        env:
           TARGET: windows
           ARCH: ${{ matrix.arch }}
           SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run:
          ./bsys6 package setup msix portable nupkg

      - name: Upload artifacts
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: windows-${{ matrix.arch }}
          path: |
            *.zip
            *.exe
            *.msix
            *.nupkg
            *.sha256sum
          retention-days: 7

  build-macos:
    runs-on: epsilon
    container:
      image: codeberg.org/librewolf/bsys6:macos 
    strategy:
      matrix:
        arch: [x86_64, arm64]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build MacOS
        env:
           TARGET: macos
           ARCH: ${{ matrix.arch }}
           SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run:
          ./bsys6 package

      - name: Upload artifacts
        uses: https://data.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: macos-${{ matrix.arch }}
          path: |
            *.tar.xz
            *.dmg
            *.sha256sum
          retention-days: 7

  publish-release:
    runs-on: epsilon
    container:
      image: codeberg.org/librewolf/bsys6:release
    needs: [build-linux, build-windows, build-macos]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: https://data.forgejo.org/forgejo/download-artifact@v4
        with:
          merge-multiple: true

      - name: Publish Release
        env:
           FORGE_USER: ${{ vars.FORGE_USER }}
           FORGE_TOKEN: ${{ secrets.FORGE_TOKEN }}
           FORGE_REPO: ${{ forgejo.repository }}
           FORGE_REPO_OWNER: ${{ forgejo.repository_owner }}
           REPO_DEPLOY_TOKEN: ${{ secrets.REPO_DEPLOY_TOKEN }}
           GH_TOKEN: ${{ secrets.GH_TOKEN }}
           CHOCO_API_KEY: ${{ secrets.CHOCO_API_KEY }}
           MS_CLIENT_SECRET: ${{ secrets.MS_CLIENT_SECRET }}
           SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run:
          ./bsys6 release