FROM debian:trixie-slim

ARG VERSION
ARG FORGE_URL=https://librewolf.dev
ARG FORGE_REPO_OWNER=librewolf
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3-pip rpm gnupg jq nodejs ruby git-lfs curl xz-utils pigz \
        file appstream binutils tar make unzip ca-certificates patch s3cmd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    gem install fpm && gem cleanup && \
    # Download LibreWolf source
    curl -qfA "" --no-sessionid --proto =https --tlsv1.2 \
        ${FORGE_URL}/api/packages/${FORGE_REPO_OWNER}/generic/librewolf-source/${VERSION}/librewolf-${VERSION}.source.tar.gz -o librewolf-${VERSION}.source.tar.gz \
        ${FORGE_URL}/api/packages/${FORGE_REPO_OWNER}/generic/librewolf-source/${VERSION}/librewolf-${VERSION}.source.tar.gz.sha512sum -o librewolf-${VERSION}.source.tar.gz.sha512sum && \
    sha512sum -c librewolf-${VERSION}.source.tar.gz.sha512sum && \
    tar -xf librewolf-${VERSION}.source.tar.gz && \
    rm librewolf-${VERSION}.source.tar.gz librewolf-${VERSION}.source.tar.gz.sha512sum && \
    # Download needed build artifacts
    ./librewolf-${VERSION}/mach artifact toolchain --from-build \
        linux64-clang-23 sysroot-x86_64-linux-gnu linux64-pkgconf \
        linux64-cbindgen linux64-node-24 linux64-nasm sysroot-wasm32-wasi-clang-23 \
        onnxruntime-x86_64-linux-gnu sysroot-aarch64-linux-gnu && \
    # Move artifacts to .mozbuild
    mv clang sysroot-x86_64-linux-gnu pkgconf \
        cbindgen node nasm sysroot-wasm32-wasi \
        onnxruntime-x86_64-linux-gnu sysroot-aarch64-linux-gnu /root/.mozbuild/ && \
    # Install rust
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile minimal --default-toolchain 1.99 --target aarch64-unknown-linux-gnu && \
    # Install appimagetool
    curl -fL "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage" -o "appimagetool" && \
    chmod +x appimagetool && \
    mv appimagetool /usr/local/bin/ && \
    # Install the type2-runtime
    curl -fL "https://github.com/AppImage/type2-runtime/releases/download/continuous/signing-pubkey.asc" -o "signing-pubkey.asc" && \
    gpg --import signing-pubkey.asc && \
    curl -fL "https://github.com/AppImage/type2-runtime/releases/download/continuous/runtime-x86_64" -o "runtime-x86_64" && \
    curl -fL "https://github.com/AppImage/type2-runtime/releases/download/continuous/runtime-x86_64.sig" -o "runtime-x86_64.sig" && \
    curl -fL "https://github.com/AppImage/type2-runtime/releases/download/continuous/runtime-aarch64" -o "runtime-aarch64" && \
    curl -fL "https://github.com/AppImage/type2-runtime/releases/download/continuous/runtime-aarch64.sig" -o "runtime-aarch64.sig" && \
    gpg --verify runtime-x86_64.sig runtime-x86_64 && \
    gpg --verify runtime-aarch64.sig runtime-aarch64 && \
    rm signing-pubkey.asc runtime-x86_64.sig runtime-aarch64.sig && \
    mv runtime-x86_64 /usr/local/lib/appimage-runtime-x86_64 && \
    mv runtime-aarch64 /usr/local/lib/appimage-runtime-aarch64 && \
    # Cleanup
    rm -rf \
        /root/.mozbuild/toolchains librewolf-${VERSION} \
        /root/.mozbuild/srcdirs /root/.mozbuild/mach_func_cache \
        /root/.mozbuild/glean /root/.cache
