FROM debian:trixie-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl ca-certificates && \
    curl -qfA "" --no-sessionid --proto =https --tlsv1.2 https://vcs.fi/api/packages/OSSign/debian/repository.key -o /etc/apt/keyrings/forgejo-OSSign.asc && \
    echo "deb [signed-by=/etc/apt/keyrings/forgejo-OSSign.asc] https://vcs.fi/api/packages/OSSign/debian stable main" > /etc/apt/sources.list.d/forgejo.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        gnupg lsb-release nodejs s3cmd ossign gawk git libnss3-tools libnss3 libnspr4 \
        make lbzip2 zip mono-complete jq gettext-base python3-pip xz-utils && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    # Install signmar
    curl -fL "https://sentinel.dev/api/packages/sentinel/generic/signmar/latest/signmar" -o "signmar" && \
    echo "79481e9f66b44fb3923d4ac7dec9fb646b2a613c99dbb447610bcc83e760de0f90a6f7caae6bf68bd25c201505c4a77634977d613004bc9c7ed1737717bda59e signmar" | sha512sum -c - && \
    chmod +x signmar && \
    mv signmar /usr/local/bin/ && \
    rm -rf /root/.mozbuild/chocolatey && \
    mkdir -p /root/.mozbuild/chocolatey && \
    curl -qfLA "" --no-sessionid --proto =https --tlsv1.2 https://github.com/chocolatey/choco/releases/download/2.7.2/chocolatey.v2.7.2.tar.gz | \
    tar -C /root/.mozbuild/chocolatey -xz && \
    printf '#!/bin/bash\nset -e\nmono "$(dirname $(readlink -f "$0"))/choco.exe" "$@"\n' > /root/.mozbuild/chocolatey/choco && \
    chmod +x /root/.mozbuild/chocolatey/choco && \
    pip3 install --break-system-packages azure-storage-blob
