FROM debian:trixie-slim

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends curl ca-certificates && \
    curl -qfA "" --no-sessionid --proto =https --tlsv1.2 https://pkg.ossign.org/debian/repository.key -o /etc/apt/keyrings/gitea-ossign.asc && \
    echo "deb [signed-by=/etc/apt/keyrings/gitea-ossign.asc] https://pkg.ossign.org/debian all main" > /etc/apt/sources.list.d/ossign.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        gnupg lsb-release nodejs s3cmd ossign gawk git \
        make lbzip2 zip mono-complete jq gettext-base python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /root/.mozbuild/chocolatey && \
    mkdir -p /root/.mozbuild/chocolatey && \
    curl -qfLA "" --no-sessionid --proto =https --tlsv1.2 https://github.com/chocolatey/choco/releases/download/2.7.2/chocolatey.v2.7.2.tar.gz | \
    tar -C /root/.mozbuild/chocolatey -xz && \
    printf '#!/bin/bash\nset -e\nmono "$(dirname $(readlink -f "$0"))/choco.exe" "$@"\n' > /root/.mozbuild/chocolatey/choco && \
    chmod +x /root/.mozbuild/chocolatey/choco && \
    pip3 install --break-system-packages azure-storage-blob