#!/bin/sh
set -e

case "$1" in
configure|abort-upgrade)
  if [ -x /usr/bin/librewolf ]; then
    update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/bin/librewolf 70 || true
    update-alternatives --install /usr/bin/gnome-web-browser gnome-web-browser /usr/bin/librewolf 70 || true
  fi
;;
esac

if command -v cmp >/dev/null 2>&1; then
  if cmp -s /etc/apparmor.d/local/librewolf /etc/apparmor.d/librewolf; then
    : > /etc/apparmor.d/local/librewolf
  fi
fi

if command -v dpkg-query >/dev/null 2>&1; then
  ver=$(dpkg-query -W -f='${Version}\n' apparmor)
  if dpkg --compare-versions "$ver" lt "4.0"; then
    rm -f /etc/apparmor.d/librewolf
  fi
fi


if command -v systemctl >/dev/null 2>&1; then
  if systemctl list-unit-files | grep -q '^apparmor\.service'; then
    systemctl restart apparmor.service || true
  fi
fi

exit 0
